image: continuumio/anaconda3:5.0.1

before_script:
  - python -V                                   # Print out python version for debugging
  - apt-get update
  - apt-get install -y build-essential
  - pip install cython Deprecated==1.1

run:
  tags:
  - docker
  script:
  - python waf configure --prefix=install --enable-debugging
  - python waf build
  - python waf install
  - (cd modules/python/cython; python setup.py bdist_wheel)
  artifacts:
    paths:
    - install/*
    - modules/python/cython/dist/*.whl
