name: build_unittest

on: [push]

jobs:
  build-windows:
    name: Windows
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        ls env:
        mkdir target
        cd target
        cmake .. -DCMAKE_INSTALL_PREFIX=installWindows-Github -DPYTHON_VERSION="3.7"
    - name: build
      run: |
        cd target
        cmake --build . --config Release -j
    - name: install
      run: |
        cd target
        cmake --build . --config Release --target install
    - name: test
      run: |
        cd target
        ctest -C Release


  build-linux:
    name: Linux
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        env
        which python
        mkdir target
        cd target
        cmake .. -DCMAKE_INSTALL_PREFIX=installLinux-Github -DPYTHON_VERSION=3.7
    - name: build
      run: |
        cd target
        cmake --build . -j
    - name: install
      run: |
        cd target
        cmake --build . --target install
    - name: test
      run: |
        cd target
        ctest
