name: Build, unittest

on: [push]


jobs:
  build-cmake-windows:
    strategy:
      matrix:
        os: [windows-latest]
    name: ${{ matrix.os }}-CMake
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        mkdir target-Release
        cd target-Release
        cmake -DCMAKE_INSTALL_PREFIX=install${{ matrix.os }}CMake-Github -DPYTHON_VERSION="3.7" ..
    - name: make
      run: |
        cd target-Release
        cmake --build . --config Release -j
        cmake --build . --config Release --target install
    - name: test
      run: |
        cd target-Release
        ctest -C Release --output-on-failure
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: msbuild
      run: |
        msbuild nitro.sln /p:configuration=Release

  build-msbuild-windows:
    strategy:
      matrix:
        os: [windows-latest]
        platform: [x64]
        configuration: [Release]
    name: ${{ matrix.os }}-msbuild-${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: configure CODA-OSS
      run: |
        mkdir externals\coda-oss\out
        cd externals\coda-oss\out
        cmake -DCMAKE_INSTALL_PREFIX=install\${{ matrix.platform }}-${{ matrix.configuration }} -DENABLE_PYTHON=OFF ..
    - name: make CODA-OSS
      run: |
        cd externals\coda-oss\out
        cmake --build . --config ${{ matrix.configuration }} -j
        cmake --build . --config ${{ matrix.configuration }} --target install
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: msbuild
      run: |
        msbuild nitro.sln /p:configuration=${{ matrix.configuration }}
    - name: vstest # https://github.com/marketplace/actions/vstest-action
      uses: microsoft-approved-actions/vstest@master
      with:
          testAssembly: UnitTest.dll
          searchFolder: .\${{ matrix.platform }}\${{ matrix.configuration }}
          runInParallel: true  

  build-linux-cmake:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: ${{ matrix.os }}-CMake
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        mkdir target-Release
        cd target-Release
        cmake -DCMAKE_INSTALL_PREFIX=install${{ matrix.os }}CMake-Github -DPYTHON_VERSION=3.7 ..
    - name: make
      run: |
        cd target-Release
        # using the default number of threads (-j) causes G++ to crash
        cmake --build . -j 6
        cmake --build . --target install
    - name: test
      run: |
        cd target-Release
        ctest --output-on-failure
