name: Build, unittest

on: [push]


jobs:
  build-windows:
    name: Windows
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        mkdir out
        cd out
        cmake -DCMAKE_INSTALL_PREFIX=installWindows-Github -DPYTHON_VERSION="3.7" ..
    - name: make
      run: |
        cd out
        cmake --build . --config Release -j
        cmake --build . --config Release --target install
    - name: test
      run: |
        cd out
        ctest -C Release --output-on-failure
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: msbuild
      run: |
        msbuild nitro.sln /p:configuration=Release
    #- name: mstest
    #  run: |
        # mstest /testcontainer:${RUNNER_WORKSPACE}\coda-oss\x64\Releast\Test.dll
        # mstest /testcontainer:${RUNNER_WORKSPACE}\coda-oss\x64\Releast\Test++.dll

  build-linux:
    name: Linux
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        mkdir out
        cd out
        cmake -DCMAKE_INSTALL_PREFIX=installLinux-Github -DPYTHON_VERSION=3.7 ..
    - name: make
      run: |
        cd out
        # using the default number of threads (-j) causes G++ to crash
        cmake --build . -j 6
        cmake --build . --target install
    - name: test
      run: |
        cd out
        ctest --output-on-failure
